version: '3.8'

services:

  mysql:
    image: mysql:8.0
    container_name: product-catalog-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: product_catalog
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10

  backend:
    build: ./product-catalog/product-catalog
    container_name: product-catalog-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/product_catalog?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build: ./product-catalog-frontend
    container_name: product-catalog-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  mysql_data: